M48
; DRILL file {KiCad 8.0.3} date 2024-06-09T12:16:39+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-09T12:16:39+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X71.084Y-78.1
X71.084Y-84.9
T2
X72.084Y-72.5
X72.084Y-117.5
X117.084Y-117.5
M30
