[package]
name = "chip8"
version = "0.1.0"
authors = ["Pietro Lorefice <pietro.lorefice@gmail.com>"]
edition = "2018"

[dependencies]
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
